language: java
sudo: required
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: QDaAH8/KVGPEwH69AfE7+I42Icm711Ze83TSQbI8wXiiTicvWZW6TjlPP0G5FjDDquKthZfqH6Ny1tvtOku6d6GmnpNLB+Cr+9QUuzo1YSQY8kY2owI9zcUjFBkb+k7hE4bmKdSzlZdiUyVWIJAi9a06T1eWAmP5pqiDWeSOBnafW2+z8b9Gm73d1rAMTZUTA+EzLGAxh3MoojQzFhse3tbn+PGJ4Oih7/hx1skOiw36Hk7SOYPceSoUgEfFlZJuQktW2VlXAlAYXq6lYsVxtmcSxABVBSnaSmFZ+y5GtkciACEG+tlRA8EVk1hrf1yKhxbqIZwtP6cRgEN3c0tqI6IT5Un7aNSh2r7HtpqJcXVMvHpByFdb8jVJmsXlxUXZvVBm9csO23gYiYm08UdF29zoYo4rIx1YBXTlYOAHNy21QWoy0rQCiZaNno0SeynF0Uc5385gRdGSLa+7vRo4I/G7GXx9z36w7NUVRvCDQktrriH6mh3oajcLROTsptaTC1v02n1Uv/M99GpkOkw+HmQuBujCWPUQ/9SFi15kD58bYhLG7zVeLlmD8nsYg53OdCmQLkUuOlh6dkWVgvALGqJLQNpk+zO9tRv3xetKhbsHPLCwK74vgxbJADJ7ZEeSjA8W4hrMb4N5ZWwnsFX7jDAr8YhSLoWFo20sABpPpak=
install:
- cd desapp-groupA-backend && mvn install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
