language: java
sudo: required
jdk:
- oraclejdk8
script:
- cd desApp-groupA-backend && ./mvnw clean install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8 && ./mvnw  test -B
deploy:
  provider: heroku
  api_key:
    secure: g/CPKU1a6n1bohkBkoc714V4cxxfoN09iS33fT4PJHiNmO8/aUaFKY2qijjtc66Q5EXgBNvq+Z9Czu2h7fgp2ZkwVTm7Mj/uKuWQ8n79r4/Ko2KSiUHIr49bM7NvUFX+2TdYbdqUDIEf+aibK7ypunUEIGOBhcpnY/gyjCU6YhY8fhKaw13yE77zck+GNd6x3p6FeYgZ0HBgQThuSXFvwsJa6Ukubn5DlZgah/l8qgYIP01e47TQvrWNqKu13b+UcCkAgJcp0BmZG15IOteS5EUUw6VRaBW7h4P+NeeeGroCYAxSz/ZiMHheHfG1rwYOLo/SFAXkjxBztXm3iRDE2YE9+7YEOTRbN1lAGdToInIMBqXfVqHH7dCFEMg4fxX2WLyH+9Jv/yLbXQfh3ejdEyemmyFWuZ1jx7majT3GijfxJ4KrtUhVqO4tmHD8LQzrLW/gt/M4THB78Ixjq+himAXB+DEoG4an1ut3jsi0jkkdY92u5Et7s22kBpHTg/Pw1cjSWvchOj288rpZfAXwJAGdpLoML+AD7cG4iuGr5du44CjhjBB2tb5uOf450IqTN60zZ7ulxc5z0FWqEy7b7FbRV3WzUkrCvRM/VI4Z29KbqVbVGyRXOMCjNK0okxdqOsvIffGC7rhpHKmjBwR8rxY9eP/925Hx8kHwP78KlQc=
  app: grupo-a-012017
  on:
    repo: lucianofedericoolmedo/Grupo-A-01-2017
repo: lucianofedericoolmedo/Grupo-A-01-2017

after_success:
- mvn clean test jacoco:report coveralls:report